### ISSUE TITLE
Is Snow right for my use case?

### ISSUE THREAD

**Issue by pieterdd** [mcginty/snow#160]
Cryptography's a bit intimidating to me. Since the Snow documentation seems geared towards an audience that already understands Noise, I figured I'd ask a newbie question here.

For an opensource application that exchanges data between nodes on the same network, I'd like to implement an encrypted application-layer protocol where authentication is handled SSH-style:
- Communication is encrypted using public/private key crypto
- Any client may attempt to connect to any server without needing anything other than a generated keypair
- On connect, the client and server decide whether they trust each other's public key (based on an allowlist or explicit user prompt)

Is Snow suitable for this? If yes, which configuration should I use? The example I viewed seems to use a [symmetric static key](https://github.com/mcginty/snow/blob/master/examples/simple.rs#L48), which due to the nature of open source wouldn't be secret in my case.

**Comment by Yoga07** [comment]
I'm not sure if this issue is outdated/valid anymore, but as an FYI, the example in the crates uses Noise's XX pattern to establish an encrypted connection using asymmetric keys. This should now cover all of your concerns mentioned above.

You can take a look at [Noise's XX handshake pattern](https://noiseexplorer.com/patterns/XX/#) which uses the Diffie-Hellman Key Exchange algorithm to see how a secure connection is established.
