### ISSUE TITLE
Support deferred patterns

### ISSUE THREAD

**Issue by mcginty** [mcginty/snow#23]

**Comment by Mandragorian** [comment]
Hello,

I am a CS Master's student focusing on security and cryptography. I know Rust but I would like to get better at it. Can I help with this issue (or something else?)

**Comment by mcginty** [comment]
@Mandragorian Welcome! Yes, you can certainly help with this issue. It seems like a good starting task at first glance if you want something more than just a tiny bugfix to take on.

It looks like the Haskell implementation of Noise recently added deferred patterns recently, so https://github.com/centromere/cacophony/commit/18b7348c54fd61fcd0c220298883de0d09c8364d is probably a good starting point, and testing against their new test vectors would be a good step towards checking if your implementation is correct before even putting it up for a PR.

I'm not currently working on this, and nobody else is as far as I'm aware, so feel free to take a shot at it.

**Comment by Mandragorian** [comment]
Hello again,

I am running my code against the test vectors from cacophony. Specifically I am testing the `NK1` pattern. According to the framework's specification the `NK1` pattern is defined as

    NK1:
      <- s
      ...
      -> e
      <- e, ee, es

So in my code I have 

```rust
NK1 => (                                                            
  static_slice![Token: ],                                           
  static_slice![Token: S],                                         
  message_vec![&[E], &[E, Dhee, Dhes]],
)
```

However this results in the tests failing with the message `write_message failed on message 1
`. After putting some `println!`s the reason for the failure is because in the `HandshakeState::dh` the expression `remote_s || self.rs.is_on()` in the first `if` statement evaluates to false.

If I change the rust code where the pattern is defined to 

```rust
NK1 => (                                                            
  static_slice![Token: ],                                           
  static_slice![Token: S],                                         
  message_vec![&[E], &[E, Dhee, Dhse]],
)
```

The test passes. After looking at the code more carefully, I noticed that the `es` and `se` tokens are changed in some other placed also, for example in the definition of the `NX` pattern. Is this on purpose? I believe that this happens when the token is written in a responder's message. Does this happen because the canonical form changes?

**Comment by mcginty** [comment]
@Mandragorian sorry for the delay in responding! This is left from the original rust noise implementation, and I wanted to keep these low-level internals as close to the reference parent as possible. Maybe @trevp can comment on why it was like this originally, but I agree it seems best to make the patterns looking as close to the specification as possible.

**Comment by Mandragorian** [comment]
Thanks for the explanation. Then I would suggest that this issue is resolved without changing how the `Dhes` and `Dhse` tokens are used internally. Then you can open a separate issue for bringing the patterns' form closer to the specification, if you deem it necessary.

**Comment by trevp** [comment]
The Noise spec used to define the meaning of the "es" and "se" patterns based on the sender of that particular message.  That was hard to read, so we changed them to refer to the initiator/responder roles.  This code pre-dates that, but it would certainly be easier to read if it was changed to match the current spec.
