### ISSUE TITLE
deprecate rust-crypto / wasm

### ISSUE THREAD

**Issue by aep** [mcginty/snow#33]
whats your opinion on the state of rust-crypto? it doesnt look well maintained and doesnt compile for webassembly. there's an unpopular but maintained fork here that does https://github.com/buttercup/rust-crypto-wasm

this stuff is maintained https://github.com/RustCrypto but would require picking libraries for individual parts.

- [x] CSPRNG https://github.com/RustCrypto/CSRNGs
- [x] 25519 https://github.com/dalek-cryptography/ed25519-dalek
- [ ]  curve 448: couldnt find anything
- [ ] AES https://github.com/RustCrypto/block-ciphers
- [ ]  chacha20: this looks dead, but slightly less dead than crypto-wasm https://github.com/cesarb/chacha20-poly1305-aead
- [x] SHA256/SHA512 https://github.com/RustCrypto/hashes
- [x] BLAKE2 https://github.com/RustCrypto/hashes

**Comment by mcginty** [comment]
yeah I'd really like to phase out rust-crypto as rust implementations become available. I'm very interested in replacing the remaining pieces with competent implementations (ex. curve25519-dalek).

I'll have to check out this wasm fork to see what kinds of changes they made, haven't heard of it up until now.

**Comment by aep** [comment]
in the meantime the PR might be an OK quickfix. it enables the fork only for wasm.

**Comment by aep** [comment]
@mcginty seems to work for me. should we go ahead with that PR?

**Comment by mcginty** [comment]
Hey sorry for being less responsive, I'm traveling more intensely for the next couple weeks. Let's take a look at that PR.

**Comment by mcginty** [comment]
Your code seems fine, but there's some smell in the `rust-crypto-wasm` crate that makes me on edge.

First, they haven't updated the `README` or crate metadata, which makes this crate seem more like a dirty workaround hack than a maintained repository.

Second, the constant time comparison implemented isn't convincingly constant time given how complicated that can be in Rust with its clever optimizer. In a nicer world it'd rely on something like [subtle](https://github.com/dalek-cryptography/subtle) instead rather than implementing in an way that's I'd imagine does not actually fix timing attacks.

Overall, I don't get the feeling that this crate should be included in its current state since it feels half-baked.

**Comment by aep** [comment]
makes sense, thanks for checking.

**Comment by mcginty** [comment]
No problem! Also unfortunately, I think the AES checkmark in your list isn't there yet either, because the RustCrypto project doesn't implement GCM.

Also, we already use https://github.com/cesarb/chacha20-poly1305-aead for chacha20poly1305, and the same author of that wrote the BLAKE library we are using as well.

**Comment by aep** [comment]
could you open a bug in the meantime? Maybe someone else could work on the GCM. If thats the only part missing, that sounds pretty good!

**Comment by aep** [comment]
this is currently blocking me from porting to aaarch64 and mipsel. any idea what the state is?

**Comment by mcginty** [comment]
rustls uses ring as its crypto provider. does ring not compile for aarch64 and mipsel I take it?

**Comment by aep** [comment]
ah, that makes sense of course. no ring isnt that portable unfortunately.

**Comment by aep** [comment]
hacl compiles, however:

    Init { reason: GetRngImpl }

looks like thats just missing:

https://github.com/mcginty/snow/blob/da3675fbb03a753cc758dc09717fa6d03fe9276f/src/resolvers/hacl_star.rs#L19

should i add this using the rand crate?

**Comment by mcginty** [comment]
You can do this using the existing snow just by using `FallbackResolver` and a custom resolver that only resolves the RNG to an instance from the rand crate (can just copy that part from the default resolver).

I'd like to keep the HACL* resolver as-is because it would only make sense to resolve the RNG in that impl if it's a HACL*-specific RNG, in my opinion.

**Comment by aep** [comment]
got it. unfortunately hacl has no aesgcm either. how do you feel about this one:

https://github.com/miscreant/miscreant-rs

**Comment by aep** [comment]
how do we proceed here? My proposal would be to add a new resolver that simply doesnt have aesgcm.

**Comment by mcginty** [comment]
Yeah, let's just remove our dependency on rust-crypto and not support AES-GCM in the default resolver for now, and I will look into spinning off a separate crate with just the AES-GCM support + fixes.

If you want to submit a PR, I think it's time to remove our dependency on an abandoned crypto crate.

**Comment by BlackHoleFox** [comment]
@mcginty I spent a bit of time and replaced `rust-crypto`. Its probably not the cleanest job ever, but any tips are appreciated. All the tests pass and the benchmarks run as well. Currently I can't cross-build Snow because of a error inside `rust-crypto`'s symbols. You can see my work over [here](https://github.com/BlackHoleFox/snow/tree/remove-rustcrypto). If it looks alright to start then I'd be happy to open a PR.

**Comment by mcginty** [comment]
@BlackHoleFox just skimmed it - off to a good start, left you some comments. Feel free to open a PR and I can help you finish iterating on it.

**Comment by mcginty** [comment]
#76 and #79 are related.

**Comment by mcginty** [comment]
In the mean time though, rust-crypto is no longer in this project so I'm going to go ahead and close this issue.
