### ISSUE TITLE
Noise Extension: Hybrid Forward Secrecy

### ISSUE THREAD

**Issue by david415** [mcginty/snow#39]
Are you interested in this feature?

Here's the noise fork by Yawning Angel that has the XXhfs using NewHope-Simple:

* https://github.com/katzenpost/noise

Here's the spec extension:

https://raw.githubusercontent.com/noiseprotocol/noise_spec/41d478d3dd97d77a6695f4d6cf6283e2830e9ca6/extensions/ext_hybrid_forward_secrecy.md

**Comment by mcginty** [comment]
Yes, I'm interested in adding HFS support.

**Comment by dsprenkels** [comment]
Hey all, in August/September I will probably have some time to implement this. Can I claim this issue for now?

**Comment by mcginty** [comment]
@dsprenkels go for it :).

**Comment by dsprenkels** [comment]
Here's some preliminary notes.

- Implement the latest HFS spec, i.e. the one listed at <https://github.com/noiseprotocol/noise_hfs_spec/blob/master/output/noise_hfs.pdf>.
- At request of @david415, I will use the Kyber-1024 key encapsulation scheme.
- At first, this scheme will be based on the Rust bindings to the PQClean suite of implementations. <https://github.com/PQClean/PQClean> from Kannwischer, Rijneveld, Schwabe, Stebila, Wiggers.
  - Later I intend to implement an optimized version of the Kybers in Rust.
- Moreover, as the community whether they would like to see a different cryptoscheme, and use that one as well. (In any case announce this project over the mailing list.)
- Everything will be feature gated by a `hfs` feature, s.t. these changes do not include code/compile bloat.

**Comment by dsprenkels** [comment]
Hey @mcginty, today I have worked on the HFS support. I have implemented the parsing and message pattern for the `"hfs"` modifier, which can be seen in https://github.com/dsprenkels/snow/commit/9efc2664f26e0009ca325483162da96e72a76ef2.

Up until now I found that feature-gating everything was doable. However, when I move more towards the core of the crate, I see that I may get difficult at times. One example is in [`HandShakeState::_write_messaage()`](https://github.com/mcginty/snow/blob/4a0c800e6c5bbcc6f85ad1ce402f93e074349788/src/handshakestate.rs#L185-L251). Because we cannot put attributes on the pattern matches, I would have to refactor the whole thing and fragment it into a lot of smaller functions.

https://github.com/mcginty/snow/blob/4a0c800e6c5bbcc6f85ad1ce402f93e074349788/src/handshakestate.rs#L185-L251

Do you (or anybody else) have advice/suggestions on this?

**Comment by david415** [comment]
I'd like to try out your branch... What is a valid Noise HFS specification string?
This one is not valid:
Noise_XXhfs_25519+Kyber1024_ChaChaPoly_BLAKE2b

**Comment by dsprenkels** [comment]
Because Trevor's spec did not mention anything about the `+`-syntax, I have currently implemented the resolving in a way that you have to specify the KEM separately in the builder. Let me give an example:

```rust
 let params: NoiseParams = "Noise_NNhfs_25519_ChaChaPoly_SHA256".parse().unwrap();
    let mut h_i = Builder::new(params.clone())
        .kem(KemChoice::Kyber1024)
        .build_initiator()
        .unwrap();
```

In this case, the resolver is the default resolver (not `ring`).

**Comment by david415** [comment]
Shouldn't this work?

```
[dependencies.snow]
git = "https://github.com/dsprenkels/snow"
branch = "hfs"
default-features = false
features = ["default-resolver", "hfs", "pqclean_kyber1024"]
```

Attempted and failed to use Kyber1024 in this branch of mix_link:

https://github.com/sphinx-cryptography/mix_link/tree/with_kyber.0

**Comment by david415** [comment]
Hi all. I'm looking forward to this feature getting landed. No hurry I'm just saying that I'm looking forward. Cheers!

**Comment by mcginty** [comment]
This is now merged in master.
